#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'couchdb',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'erlang',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'git',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'nginx',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'redis',
  :git => 'https://github.com/scalarium/example-cookbooks'
cookbook 'unicorn',
  :git => 'https://github.com/opscode/cookbooks'
cookbook 'wkhtmltopdf',
  :git => 'https://github.com/Nextfave/cookbooks.git'
cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git'
cookbook 'munin',
   :git => 'git@github.com:dmytro/munin-solo.git'

# cookbook 'chef-client'

cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
